import { observer } from 'mobx-react';
import cx from 'classnames';

import TopDesktopImg from 'src/asset/top-desktop.png';
import TopMobileImg from 'src/asset/top-mobile.png';
import BottomImg from 'src/asset/bottom-img.svg';
import TopPadImg from 'src/asset/top-pad.png';
import Icon1 from 'src/asset/icon-1.svg';
import Icon2 from 'src/asset/icon-2.svg';
import Icon3 from 'src/asset/icon-3.svg';
import Icon4 from 'src/asset/icon-4.svg';

import s from './Main.module.scss';

const Advantages = [
    {
        icon: Icon1,
        title: 'Unleash LSD Liquidity',
        description: 'Borrow EUSD against LSDs for DeFi. More applications, more possibilities.'
    },
    {
        icon: Icon2,
        title: 'High Capital Efficiency',
        description: 'Higher than MakerDAO by 150%.'
    },
    {
        icon: Icon3,
        title: 'Lowest interest rate 0.25%',
        description: 'Encourages long-term holding. Annual interest rate of 0.25% for holding for one year.'
    },
    {
        icon: Icon4,
        title: 'Decentralized',
        description: 'Generated by ETH and LSD collateral only. Completely decentralized.'
    }
];

export default observer(function Main() {

    const LaunchApp = () => {
        window.open('https://app.erd.xyz', '_target');
    };

    return (
        <div className={s.wrap}>
            <div className={s.topWrap}>
                <div className={cx(s.topDesktopImg, s.topImg)}>
                    <img src={TopDesktopImg} alt='' />
                </div>
                <div className={cx(s.topPadImg, s.topImg)}>
                    <img src={TopPadImg} alt='' />
                </div>
                <div className={cx(s.topMobileImg, s.topImg)}>
                    <img src={TopMobileImg} alt='' />
                </div>
                <div className={s.productInfo}>
                    <div className={s.slogan}>
                        <div>
                            <p className={s.first}>On</p>
                            <p>Ethereum.</p>
                        </div>
                        <div>
                            <p className={s.first}>By</p>
                            <p>Ethereum.</p>
                        </div>
                        <div>
                            <p className={s.first}>For</p>
                            <p>Ethereum.</p>
                        </div>
                    </div>
                    <p className={s.name}>Ethereum Reserve Dollar</p>
                    <div className={s.launchBtn} onClick={LaunchApp}>Launch App</div>
                </div>
            </div>
            <div className={s.mask} />
            <p className={s.title}>
                The Main Advantages Of The ERD
            </p>
            <div className={s.bottomImg}>
                <img src={BottomImg} alt='' />
            </div>
            <div className={s.advantages}>
                {Advantages.map((advantage) => {
                    return (
                        <div key={advantage.title} className={s.advantage}>
                            <img src={advantage.icon} alt='' />
                            <p className={s.advantageTitle}>{advantage.title}</p>
                            <p className={s.advantageDesc}>{advantage.description}</p>
                        </div>
                    );
                })}
            </div>
        </div>
    );
});
